{
 "title": "Query Gateway Dashboard",
 "tags": [
  "query_gateway",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "datasets",
    "query": "label_values(portal_stream_bytes_sum, dataset_id)"
   },
   {
    "name": "group",
    "query": "label_values(portal_stream_bytes_sum, $group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(portal_streams_completed_total[$__rate_interval]))",
     "legendFormat": "Completed"
    },
    { "expr": "sum(portal_streams_active)", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Query responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(portal_queries_responded_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(portal_queries_sent_total[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    { "expr": "sum(portal_queries_running)", "legendFormat": "Active" },
    {
     "expr": "sum(rate(portal_queries_backoff_hints_total[$__rate_interval]))",
     "legendFormat": "Hit rate limit"
    }
   ]
  },
  {
   "title": "Known workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(portal_known_workers)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(transport_active_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pings per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(portal_pings_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ignored pings per second",
   "type": "stat",
   "description": "These pings are coming from workers with unsupported versions.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(portal_ignored_pings_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{name=\"docker-query_gateway-1\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{name=\"docker-query_gateway-1\"})"
    }
   ]
  },
  {
   "title": "/stream responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(status) (increase(portal_http_status_total{endpoint=\"/stream\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/stream delays",
   "type": "timeseries",
   "description": "Time to the first byte sent to the client",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(portal_http_seconds_to_first_byte_bucket{endpoint=\"/stream\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(portal_http_seconds_to_first_byte_bucket{endpoint=\"/finalized-stream\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(portal_http_seconds_to_first_byte_bucket{endpoint=\"/finalized-stream\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(portal_http_seconds_to_first_byte_bucket{endpoint=\"/finalized-stream\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(portal_http_seconds_to_first_byte_bucket{endpoint=\"/finalized-stream\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "max by (exported_endpoint) (rate(portal_http_latency_sum{endpoint=\"/finalized-stream\"}[1m]) / rate(portal_http_latency_count{endpoint=\"/finalized-stream\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Stream durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(portal_stream_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(portal_stream_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(portal_stream_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(portal_stream_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(portal_stream_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Throughput per stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(portal_stream_bytes_per_second_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(portal_stream_bytes_per_second_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(portal_stream_bytes_per_second_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(portal_stream_bytes_per_second_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(portal_stream_bytes_per_second_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(portal_stream_bytes_per_second_sum[$__rate_interval])) / sum(rate(portal_stream_bytes_per_second_count[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Data streamed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(dataset_id, $group) (rate(portal_stream_bytes_sum{dataset_id=~\"$datasets\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data streamed (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(portal_stream_bytes_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data streamed (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(portal_stream_bytes_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks streamed per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by($group, dataset_id) (rate(portal_stream_blocks_sum{dataset_id=~\"$datasets\"}[$__rate_interval]))",
     "legendFormat": "{{dataset_id}}"
    }
   ]
  },
  {
   "title": "Blocks streamed per second (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(portal_stream_blocks_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunks per stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(portal_stream_chunks_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(portal_stream_chunks_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(portal_stream_chunks_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(portal_stream_chunks_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(portal_stream_chunks_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Blocks per stream",
   "type": "timeseries",
   "description": "Total value for chosen datasets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(portal_stream_blocks_bucket{dataset_id=~\"$datasets\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(portal_stream_blocks_bucket{dataset_id=~\"$datasets\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(portal_stream_blocks_bucket{dataset_id=~\"$datasets\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(portal_stream_blocks_bucket{dataset_id=~\"$datasets\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(portal_stream_blocks_bucket{dataset_id=~\"$datasets\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(portal_stream_blocks_sum{dataset_id=~\"$datasets\"}[$__rate_interval])) / sum(rate(portal_stream_blocks_count{dataset_id=~\"$datasets\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Dataset lag (blocks)",
   "type": "timeseries",
   "description": "How many last known blocks are missing from the workers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by(dataset_id) (portal_dataset_storage_highest_block{dataset_id=~\"$datasets\"} - portal_dataset_highest_block{dataset_id=~\"$datasets\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gap depth (blocks)",
   "type": "timeseries",
   "description": "The position of the first gap relative to the last existing block",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(dataset_id) (portal_dataset_highest_block{dataset_id=~\"$datasets\"} - portal_dataset_first_gap{dataset_id=~\"$datasets\"} + 1)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hotblocks storage used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$persistentvolumeclaim\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful queries by peer_id",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(worker) (rate(portal_queries_responded_total{status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Portal Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "portal_streams_active{job=\"query_gateway\"}",
     "legendFormat": "Active Streams"
    }
   ]
  }
 ]
}